config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_actionをApplicationControllerに定義することで、ApplicationControllerを継承しているコントローラー内の全てのアクションが実行される前に、before_actionが実行される
#ログイン済みユーザーにのみアクセスを許可(ログインしていない場合はログイン画面にリダイレクトする) 
 # before_action :authenticate_user!

# deviseにまつわる画面に行った時に、という意味がある。こうすることで全ての画面でconfigure_permitted_parametersをするのを防いでいる
before_action :configure_permitted_parameters, if: :devise_controller?
protect_from_forgery with: :exception

	 # ログイン後の挙動
	def after_sign_in_path_for(resource)
		user_path(resource)
	end
	# ログアウトの後の挙動
	def after_sign_out_path_for(resource)
		root_path
	end
    
    protected
	def configure_permitted_parameters
		# deviseで設定されているstrong_parametersに対してパラメーターを追加することができる
		devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :name])
		devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :not_error, only:[:edit, :update]
  def new
  	@book = Book.new
  end

  def create
  	# パラムスはデータの受け渡し時に必要
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  		redirect_to book_path(@book.id), notice: "Book was successfully created."
  	else @books = Book.all
  		 @user = current_user
  		 render :index
  	end
  end


  def index
  	@books = Book.all
  	@book = Book.new
  	@user = current_user
  end

  def show
  	@book = Book.find(params[:id])
  	@user = current_user
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(@book), notice: "Book was successfully updated."
  	else render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "Book was successfully destroyed."
  	
  end

  private
  def not_error
	@book = Book.find(params[:id])
	if current_user.id != @book.user_id
	   redirect_to books_path
	end
  end
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :not_error, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def index
  	@users = User.all
  	@user = current_user
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "User was successfully updated"
  	else render :edit
  	end
  end

  private
def not_error
	@user = User.find(params[:id])
	if current_user.id != @user.id
	   redirect_to user_path(current_user)
	end
end

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<!-- attachment_image_tag モデル名, :_idを省略したカラム名, :fill, 横幅の数値(例: 100), 縦幅の数値, format: '拡張子名(例: jpg)', fallback(代替画像): ""  -->
<!-- fillでは表示されない場合　size: "" -->
<%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>

<table>
   <tr>
   	<th>name</th>
   	<th><%= user.name %></th>
   </tr>

   <tr>
   	<th>introduction</th>
   	<th><%= user.introduction %></th>
   </tr>
</table>

  <%= link_to edit_user_path(current_user.id) do %>
<button type="button" class= "col-xs-10 btn btn-default" aria-label="Left Align"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
  <% end %>

  <h2>New book</h2>

  <%= form_for (book) do |f| %>
  <%# ここからエラーメッセージ %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
              <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
    <%# ここまでエラーメッセージ %>

    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>

    <%= f.label :body, "Opinion" %><br>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

  <% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<%= form_for (@book) do |f| %>
    <!-- エラーメッセージ -->
	<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>

    <%= f.label :body, "Opinion" %><br>
    <%= f.text_area :body %>

    <%= f.submit "Update Book" %>

    <%= link_to "Show", book_path(@book.id) %>
    <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
          <%= render "books/list", book: @book, user: @user %>
        </div>

        <div class="col-xs-9">
			<h2>Books</h2>

			<table>
				<thead>
					<tr>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
							<% end %>
			            </td>
						<td><%= link_to book.title, book_path(book.id) %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
		<%= render "books/list", book: @book, user: @user %>
		</div>

        <div class="col-xs-9">
        	
        	<% if flash[:notice] %>
			  <p><%= flash[:notice] %></p>
			<% end %>

			<h2>Book detail</h2>

			<table>

				<tbody>
				    <tr>
				      	<td>
				      	<%= link_to user_path(@book.user) do %>
					    <%= attachment_image_tag @book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
					    <%= @user.name %>
					    <% end %>
					    </td>
					    <td><%= link_to @book.title, book_path(@book) %></td>
					    <td><%= @book.body %></td>

					    <% if @book.user_id == current_user.id %>
					    <td><%= link_to "Edit", edit_book_path(@book) %></td>
					    <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
					    <% end %>
					</tr>
				</tbody>
			</table>
	    </div>
	</div>
</div>

app/views/homes/about.html.erb
<div class="container">

<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
	<strong>Bokkers!</strong>
</h1>
</div>

app/views/homes/top.html.erb
<div class="container">

  <p id="notice">Signed out successfully.</p>

    <div class="row">
  　  <div class="col-md-offset-3 col-md-6">
        <h1>welcome to<span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In<span class="glyphicon glyphicon-book"></span><strong>Bookers,</strong><br>
	        you can share and exchange your opinions , inpressions , and emotions<br>
            about various books!</p>
      </div>
    </div>

    <div class="row">
    	<%= link_to "Log in", new_user_session_path, class:"btn btn-info" %>

    	<%= link_to "Sign up", new_user_registration_path, class:"btn btn-success" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- defaultの背景色が白なのでinverseで黒にする -->
       <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left" style="color:white;">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
                                                         <!-- link_toの場合は=ではなく:にしないとエラーになる -->
        <li><%= link_to " Home", user_path(current_user.id), class:"glyphicon glyphicon-home home" %></li>
        <li><%= link_to " Users", users_path, class:"glyphicon glyphicon-user users" %></li>
        <li><%= link_to " Books", books_path, class:"glyphicon glyphicon-book books" %></li>
        <li><%= link_to " logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out logout" %></li>
          <% else %>
        <li><%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %></li>
        <li><%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %></li>
        <li><%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %></li>
        <li><%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %></li>
        <% end %>
      </ul>
    </nav>
        
      </div>
　　</header>





  <div class="main">
    <%= yield %>
  </div>

  <footer>
      <div class="container">
        <div class="row">
          <!-- offsetは隙間（スペース）を作る -->
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
  </footer>

  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for (@user) do |f| %>
<!-- エラーメッセージ -->
	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= f.label :name, "Name" %><br>
    <%= f.text_field :name %>

    <%= f.label :profile_image, "Image" %><br>
    <%= f.attachment_field :profile_image %>

    <%= f.label :introduction, "Introduction" %><br>
    <%= f.text_area :introduction %>

    <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  	<div class="col-xs-3">
      <%= render "books/list", book: @book, user: @user %>
    </div>

		<div class="col-xs-9">
			<h2>Users</h2>

			<table>
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %></td>
					<td><%= user.name %></td>

					<td><%= link_to "Show", user_path(user.id) %></td>
				</tr>
				<% end %>
			</tbody>

			</table>
		</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
          <%= render "books/list", book: @book, user: @user %>
        </div>
        <div class="col-xs-9">

			<% if flash[:notice] %>
			  <p><%= flash[:notice] %></p>
			<% end %>

			<h2>Books</h2>

			<table>
				<thead>
				  <tr>
					  <th>title</th>
					  <th>opinion</th>
					  <!-- 水平方向の統合 -->
					  <th colspan="3"></th>
				  </tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
				      <tr>
				      	<td><%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></td>
					    <td><%= link_to book.title, book_path(book.id) %></td>
					    <td><%= book.body %></td>
					  </tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>